### PR TITLE
Free up dependencies

### PR DESCRIPTION
**Pull request by lexidor**
This changes a lot of dependencies.
@tyronjung-quizlet if quizlet runs on 3.30.0 or above, this will not cause any issues. If you run a lower version, I would be able to spend some time tuning the dependencies until they work.

We nolonger have any `<?php`'s now.

### CODE REVIEW

**Comment by lexidor** [comment]
Will need more careful consideration because of the requirement to support 3.27.

**Comment by tyronjung-quizlet** [comment]
We could fork a branch for supporting older versions and move towards HHVM 4 on `master`.

**Comment by lexidor** [comment]
The would be nice. Otherwise you'd just end up with `"*"` versions or `"^3|^4"` versions for everything. Do I understand correctly that you are running 3.27? How do you use hammock then? It requires hsl 3.30...

**Comment by tyronjung-quizlet** [comment]
The Hammock version we use at Quizlet is `0.0.3`. This has HSL version `1.4.0`. We haven't updated the version used by Quizlet since we added HackTest and updated the dependencies. That's a good point though, the current version probably no longer works in Quizlet. Maybe we should fork from _before_ when HackTest was added.

**Comment by tyronjung-quizlet** [comment]
I wouldn't want Quizlet's dependency on Hammock to slow down Hammock's development for HHVM 4, especially if others are willing to use it.

**Pull request closed without merging**
